# Option
# https://goodgid.github.io/Spring-Boot-SQL-Option
# https://goodgid.github.io/Spring-Boot-SQL-Option-Show-SQL

spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false # to System Out
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: debug # to logger